apiVersion: v1
kind: Service
metadata:
  name: {{.serviceName}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{.app}}
    tier: {{.tier}}
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.deployName}}
  labels:
    app: {{.app}}
    tier: {{.tier}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.app}}
      tier: {{.tier}}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.app}}
        tier: {{.tier}}
    spec:
      containers:
      - env:
        - name: PLATE_VUE_SERVER
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{.image}}
        name: {{.app}}
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/src/api/config.js
          name: configmap-volume
          subPath: config.js
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: vue-redis
        name: configmap-volume