module.exports = {
  API_PROTOCOL: 'http',
  API_HOST: 'api.mirrormedia.mg',
  API_PORT: '80',
  DFPID: '',
  FB_APP_ID: '',
  FB_PAGES_ID: '',
  LOCAL_PROTOCOL: 'http',
  LOCAL_HOST: 'localhost',
  LOCAL_PORT: '8080',
  QUESTIONNAIRE_PROTOCOL: 'http',
  QUESTIONNAIRE_HOST: 'statics.mirrormedia.mg',
  REDIS_HOST: '',
  REDIS_PORT: '',
  REDIS_AUTH: '',
  SEARCH_PROTOCOL: 'https',
  SEARCH_HOST: '',
  SEARCH_ENDPOINT: '',
  SEARCH_API_KEY: '',
  SEARCH_API_APPID: '',
  SEARCH_API_TIMEOUT: 2000,
  SERVER_PROTOCOL: 'https',
  SERVER_HOST: 'www.mirrormedia.mg',
  TWITTER_API: {
    consumer_key: '',
    consumer_secret: '',
    access_token_key: '',
    access_token_secret: ''
  },
  YOUTUBE_PROTOCOL: 'https',
  YOUTUBE_HOST: 'www.googleapis.com/youtube/v3/playlistItems',
  YOUTUBE_PLAYLIST_ID: '',
  YOUTUBE_API_KEY: '',
  YOUTUBE_API_TIMEOUT: 2000,
}
